### ISSUE TITLE
Agent activation fails on mcollective 2.8.6 (open source puppet 4.2)

### ISSUE THREAD

**Issue by gusmat** [acidprime/r10k#254]
Hi, thanks for this module.
I'm trying to get the r10k mco agent working on mcollective 2.8.6. 
The module installs the agent in the wrong path (#245) and after fixing that and restarting MCollective it throws this error in mcollective.log:
```
D, [2015-11-06T20:35:56.043076 #3993] DEBUG -- : agents.rb:104:in `block in findagentfile' Found r10k at /opt/puppetlabs/mcollective/plugins/mcollective/agent/r10k.rb
D, [2015-11-06T20:35:56.043141 #3993] DEBUG -- : pluginmanager.rb:167:in `loadclass' Loading MCollective::Agent::R10k from mcollective/agent/r10k.rb
D, [2015-11-06T20:35:56.046595 #3993] DEBUG -- : agents.rb:67:in `loadagent' Not activating agent r10k due to agent policy in activate? method
```

This is on a Amazon Linux running ruby 2.1.7, puppet 4.2 and mcollective 2.8.6

Thanks

**Comment by gusmat** [comment]
Please ignore this issue. The problem was on the way that the binaries path was being set (via profile.d), which caused the agent to fail to find r10k.
